### ISSUE TITLE
Anbernic 35XX plus: stutters on high BPM value

### ISSUE THREAD

**Issue by igavrilov** [djdiskmachine/LittleGPTracker#100]
**OS**: muOS [2405.2 Baked Beans](https://muos.dev/release/current/baked)
**LGPT**: 1.4.1-1

## Prerequisites
- Create a project with 1 track/1 sample (i.e. break loop)
- Set BPM to 140
- Press play

## Issue details
- The app stutters after a few seconds
- Input lag increasing after a few seconds
- If set BPM to higher values (170+) the issue is more noticeable (more stutters, longer input lag)
- The issue isn't reproducible if set BPM back to 128-is value.

---
First of all I would appreciate if someone will confirm the issue is:
- Reproducible on RG35XX Plus/H/24/SP devices
- Reproducible on RG35XX OG devices
- Someone has noticed a similar issue on other devices

**Comment by djdiskmachine** [comment]
I can assert that this issue is not present on PocketCHIP, Raspberry Pi 3
I have many songs in the 160-175 BPM range

**Comment by purelygrey** [comment]
Do you mean this build? https://github.com/djdiskmachine/LittleGPTracker/pull/96 
If not which one? I have a few H700 devices and an OG 35XX lying around, and also a rather busy fast track -- I can try it out

**Comment by igavrilov** [comment]
@purelygrey yes, #96 
Here is my executable [lgpt-rg35xxplush24.arm7hf.zip](https://github.com/user-attachments/files/16751878/lgpt-rg35xxplush24.arm7hf.zip)

**Comment by igavrilov** [comment]
Alright, Knulli is 64bit so I have to build it with the [appropriate toolchain](https://github.com/knulli-cfw/toolchains/releases/tag/rg35xx-plush-sdk-20240421). The executable I shared above won't work.

**Comment by purelygrey** [comment]
@igavrilov could you please share an archive with your lgpt setup on MuOS?

**Comment by igavrilov** [comment]
@purelygrey here you go. You can install it using Archive Manager from `/mnt/mmc/ARCHIVE`:
[LGPT-1.4.1.zip](https://github.com/user-attachments/files/16838903/LGPT-1.4.1.zip)

Update muOS to [BAKED](https://dl.muos.dev/UPDATES/), the app doesn't work on REFRIED for some reason 🤷 

---
A weird thing happened: last time I used it on muOS the default key mappings worked well but this time I had to set different mapping. Anyway the app works fine (on low BPM) and the problem I described in the issue persists.

I've got troubles with building LGPT using Knulli toolchain unfortunately. Almost got to the end, still trying but got stuck on linking step. I am not very experienced in cross-compile things so If you (or anyone else) were able to build the app with the Knulli toolchain - I'd appreciate any kind of instructions/hint/directions to follow.

**Comment by djdiskmachine** [comment]
What's the error in the linking step?

**Comment by purelygrey** [comment]
I can confirm the problem on my 35XX Plus, it definitely stutters when it's over 150 bpm on MuOS Baked. It also skips on lower BPM, but way less so it's not as noticeable (tested on about 72bpm).
I tried a few things:
- forcing performance scaling governor before running LGPT
- nice --20
- setting sample rate in alsa to 44100 instead of 48000
But nothing had changed. I'll try to mess around with alsa settings a bit more just in case, and test other devices as well

**Comment by djdiskmachine** [comment]
Have you tried any of the ones from Simoteks build yesterday?
These will be available on master with some new features soon-ish

https://github.com/simotek/LittleGPTracker/releases/tag/1.4.2_Test4

**Comment by igavrilov** [comment]
@djdiskmachine No more errors after I updated to the latest master and used @simotek's toolchain 🎉

**Comment by djdiskmachine** [comment]
Fabtastic news! Have fun piggin'

**Comment by igavrilov** [comment]
I meant no more build errors. Just tried Piggy 1.4.2 on Knulli - no stutters, works smoothly (except slightly wrong key mapping).
Garlic build still has stutters issue with 1.4.2 though. Not sure is it worth to debug since we've got Piggy working on Knulli for h700 devices.

**Comment by purelygrey** [comment]
> I meant no more build errors. Just tried Piggy 1.4.2 on Knulli - no stutters, works smoothly (except slightly wrong key mapping). Garlic build still has stutters issue with 1.4.2 though. Not sure is it worth to debug since we've got Piggy working on Knulli for h700 devices.

Since I have MuOS Baked on hand I tried the @simotek's build as well, and it's doesn't stutter, awesome! I managed to caught it skipping, but it did that only once so far, it's been roughly 10 minutes, and I went for a reality check on my V90 and I caught it skipping just once as well - maybe it's some sort of quirk, I don't know. However I hear some strange tempo instabilities in my test track, like it's dragging or rushing sometimes, I'm recording audio right now for an a/b test

**Comment by purelygrey** [comment]
Turns out I'm not mad, and the same project lags a little bit on RG35XX Plus on MuOS baked, compared to BITTBOY build on Powkiddy v90, by the end of the track it gets pretty noticeable that the former is lagging behind. Also stereo channels are reversed on it for some reason (Pan 00 is right, 7F is left). Very strange, because if anything it should be the other way around, v90 is very underpowered in comparison

Here's how the lag looks like after about 1:50, roughly 29ms
![image](https://github.com/user-attachments/assets/3aeb1b84-831c-4e0a-893b-c9bb59038cf9)

Here are the recordings if you want to take a look at them
[Renders.zip](https://github.com/user-attachments/files/16841380/Renders.zip)

And the project file I'm using:
[lgpt_CoolQuestion.zip](https://github.com/user-attachments/files/16841393/lgpt_CoolQuestion.zip)

**Comment by igavrilov** [comment]
Ok, so 32-bit executable stutters, 64-bit executable works almost perfect. I believe the issue can be closed with a resolution: use 64-bit executable on muOS. muOS is actually 64bit:
```
[~]# uname -a
Linux muos-9abdd 4.9.170 #254 SMP PREEMPT Tue Dec 19 15:45:52 CST 2023 aarch64 muOS/2 NeXT
```

**Comment by djdiskmachine** [comment]
Thank you for testing and reporting your findings!

**Comment by simotek** [comment]
> Ok, so 32-bit executable stutters, 64-bit executable works almost perfect. I believe the issue can be closed with a resolution: use 64-bit executable on muOS. muOS is actually 64bit:
> 
> ```
> [~]# uname -a
> Linux muos-9abdd 4.9.170 #254 SMP PREEMPT Tue Dec 19 15:45:52 CST 2023 aarch64 muOS/2 NeXT
> ```

Sometimes its a bit confusing because i've noticed that some of the OS's are using a 64bit kernel with a 32bit userspace.
