### ISSUE TITLE
Using START and B to quickly navigate certain menus

### ISSUE THREAD

**Issue by Ekolide** [djdiskmachine/LittleGPTracker#58]
When naming a project, using Save As, or using the sample browser, it would be beneficial to have a quick way out of the menu. I suggest using `START` to navigate the cursor to the most reasonable "Okay, I'm done" button. Likewise, using the `B` button should let the user get to the most reasonable "Nah, actually never mind" button.

For the New Project naming, `START` would move the cursor to "Ok", allowing the user to start creating a new project. `B` would place the cursor on "Cancel".

For Save As, this would be the same as New Project.

For the sample browser, this gets more complex. Ideally, we would have control over starting and stopping playback, which is done with `START`. At the same time, having a way to easily get to the "EXIT" button would be beneficial. I suggest keeping playback functionality with `START`, but `B` selects the "EXIT" button. Alternatively, `B` first takes the user up the directories to the root of the sample library before selecting the "EXIT" button. 

Another menu that could benefit from accepting more user inputs is "Load Song" from the project page. The software asks "Load song and lose changes ?", to which a reasonable response might be to press `B`, as in "nah, thanks". Currently pressing `B` does nothing. I suggest pressing `B` automatically selects and executes "No". A question is whether pressing `START` should act as pressing `A`, or if it should select the "Yes" option.

**Comment by djdiskmachine** [comment]
This is mostly great, I would suggest dividing this issue to three different issues due to how this works in software.

Save As / New Project both call the same methods so this would be issue 1
Sample browser: I'm not 100% happy with the current implementation for o-beta-2, so this could go under an issue further refining it.
The notifications when loading / saving while playing has ground my gears for a while, I'd like to change this behavior quite a lot for a later release target (1.4)

**Comment by djdiskmachine** [comment]
Closed, break up to smaller tasks.
