### ISSUE TITLE
MIDI functionality

### ISSUE THREAD

**Issue by fungusB** [djdiskmachine/LittleGPTracker#79]
I've been using LGPT for a couple of weeks now and it's awesome! Thank you for maintaining and bringing it into the 2020s!

I'm experimenting with sequencing synths and drum machines via MIDI and am experiencing some bugs/quirks/missing features:

- Channel mutes do not work on MIDI channels

- it would be nice to have a MCHD command for sending chords to MIDI instruments. 
Usage would be identical to the ARPG command: Select rootnote, add up to four notes to make a chord

- VOLM command sends CC7 (channel volume) to the respective MIDI track instead of note on velocity.
While it is nice to have access to CC7 from the phrase screen, it would be great to be able to play with MIDI velocity (maybe with a MVEL command?) For example FM synths respond nicely to velocity!
Now this is probably not super trivial, as it would require to have the velocity be baked into the NOTE ON byte for each note.
 

I'm aware that MIDI is not the primary focus of LGPT, but I would be very happy to see these features implemented. I took a look at the code and was able to identify some areas of interest. My programming knowledge unfortunately is not up to the task ...

**Comment by espcam** [comment]
I'm working on host PCB for Pi Zero 2  based LittleGPTracker (will be available as open source),the  goal is to have switchable A-B midi in and out that is not available on gaming consoles, DAC will be 5102, so i really hope that basic MIDI commands and MIDI IN transport commands support will be implemented one day.

**Comment by djdiskmachine** [comment]
Fungus: I love MIDI and your suggestions are very valid. 
There has been some development on Picotracker for MIDI velocity and other things, i'll have a look at how much i can ste.. i mean be inspired by from there :)

espcam: A DIY Raspi handheld for piggy is exactly what the community needs, can't wait to see what you come up with 

I'm not currently working on Piggy due to life and things but i'll get around to it eventually, i hope you can find the patience to wait for something good 😊
Cheers!

**Comment by peterswimm** [comment]
The newest version has added velocity! https://github.com/djdiskmachine/LittleGPTracker/releases/tag/1.4.0-1

**Comment by djdiskmachine** [comment]
Broken up in
https://github.com/djdiskmachine/LittleGPTracker/issues/103
*https://github.com/djdiskmachine/LittleGPTracker/issues/104
